name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build & Start
        run: docker compose up -d --build

      - name: Wait for health
        run: |
          for i in {1..20}; do
            curl -fsS http://localhost:3000/health && exit 0
            sleep 3
          done
          echo "Service not healthy in time"
          docker compose logs --no-color
          exit 1

      - name: Hit endpoints
        run: |
          curl -fsS http://localhost:3000/health
          curl -fsS http://localhost:3000/incr

      - name: Teardown
        if: always()
        run: docker compose down -v
